/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalho5.view.article;

import trabalho5.database.Article;
import trabalho5.database.Event;
import trabalho5.view.*;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class SearchArticle extends javax.swing.JFrame {

    private final int type;
    private final ArrayList<Integer> presenter_ids;
    
    /**
     * Creates new form SearchArticle
     * 
     * @param type
     * @param name
     */
    public SearchArticle(int type, String name) {
        this.type = type;
        this.presenter_ids = new ArrayList();
        initComponents();
        
        // imprime os artigos
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        try {
            ResultSet rs;
            // SELECT ALL
            if(name.isEmpty())
                rs = Article.findViewAll(MainFrame.db);
            // SELECT By Name
            else
                rs = Article.findViewByName(MainFrame.db, name);
            while(rs.next()) {
                // armazena os ids dos apresentadores no array
                this.presenter_ids.add(rs.getInt("idPe"));
                // adiciona uma linha na tabela
                model.addRow(new Object[] {rs.getInt("idArt"), rs.getString("tituloArt"), rs.getString("dataApresArt"),
                    rs.getString("horaApresArt"), rs.getString("nomeEv"), rs.getInt("numEd"), rs.getString("nomePe")});
            }
            // fecha o cursor
            MainFrame.db.close();
        } catch(SQLException e) {
            Message msg = new Message(this, true, e.getMessage());
            msg.setTitle("Erro");
            msg.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Artigos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Data de Apresentação", "Horário de Apresentação", "Evento", "Edição", "Apresentador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable1.getColumnModel().getColumn(3).setMinWidth(140);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(5).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicia a tela de atualização ou remoção de artigo
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Pega o artigo selecionado
        int i = this.jTable1.getSelectedRow();
        try {
            // pega o código do evento
            ResultSet rs = Event.findByName(MainFrame.db, (String) this.jTable1.getValueAt(i, 4));
            Event e = Event.next(rs);
            int codEv = e.getCodEv();
            // fecha o cursor
            MainFrame.db.close();
            
            // pega o id do apresentador
            int idApr = this.presenter_ids.get(i);

            Article a = new Article((int) this.jTable1.getValueAt(i, 0), (String) this.jTable1.getValueAt(i, 1), 
                (String) this.jTable1.getValueAt(i, 2), (String) this.jTable1.getValueAt(i, 3), codEv, 
                (int) this.jTable1.getValueAt(i, 5), idApr);

            // busca os autores
            if (this.type == CRUDType.SEARCH) {
                // inicia a interface de impressão dos autores do artigo selecionado
                Authors authors = new Authors(a);
                authors.setVisible(true);
            }

            // atualização de artigo
            if (this.type == CRUDType.UPDATE) {
                // inicia a interface de atualização
                UpdateArticle updateArticle = new UpdateArticle(a);
                updateArticle.setVisible(true);
                this.dispose();
            }
            
            // remoção de artigo
            if (this.type == CRUDType.REMOVE) {
                // inicia a interface de remoção
                RemoveArticle removeArticle = new RemoveArticle(a);
                removeArticle.setVisible(true);
                this.dispose();
            }
            
        } catch(SQLException e) {
            Message msg = new Message(this, true, e.getMessage());
            msg.setTitle("Erro");
            msg.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
