/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalho5.view.report;

import trabalho5.database.Report;
import trabalho5.database.Event;
import trabalho5.view.*;

import javax.swing.table.DefaultTableModel;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;


/**
 *
 * @author Rodrigo
 */
public class GeneralReport extends javax.swing.JFrame {

    /**
     * Creates new form GeneralReport
     * @param event
     * @param edition
     */
    public GeneralReport(String event, String edition) {
        initComponents();
        
        try {
            // executa o procedimento de gerar o relatório
            Report.generate(MainFrame.db);
            
            ResultSet rs;
            // SELECT ALL events
            if (event.equals("Todos"))
                rs = Report.findViewAll(MainFrame.db);
            else {
                // pega o codEv
                rs = Event.findByName(MainFrame.db, event);
                Event ev = Event.next(rs);
                int codEv = ev.getCodEv();
                // fecha o cursor
                MainFrame.db.close();
                
                if(edition.equals("Todas"))
                    rs = Report.findViewAllEditions(MainFrame.db, codEv);
                else {
                    // pega o numEd
                    String[] parts = edition.split(" ");
                    int numEd = Integer.valueOf(parts[0]).intValue();
                
                    // SELECT ALL editions
                    if (edition.equals("Todas"))
                        rs = Report.findViewAllEditions(MainFrame.db, codEv);
                    else
                        rs = Report.findViewByEventAndEdition(MainFrame.db, codEv, numEd);
                }
            }
            
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            
            DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
            while(rs.next()) {
                model.addRow(new Object[] {rs.getInt("codEv"), rs.getInt("numEd"), rs.getString("nomeEv"), 
                    rs.getInt("inscritos"), rs.getInt("artigosApresentados"), rs.getInt("qtdPatrocinadores"), 
                    nf.format(rs.getDouble("valorTotalGanho")), nf.format(rs.getDouble("valorTotalGasto")), 
                    nf.format(rs.getDouble("saldo"))});
            }
            // fecha o cursor
            MainFrame.db.close();
            
        } catch(SQLException e) {
            Message msg = new Message(this, true, e.getMessage());
            msg.setTitle("Erro");
            msg.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Geral");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. do Evento", "Núm. Edição", "Evento", "Núm. Inscritos", "Núm. Artigos Apresentados", "Qtd. Patrocinadores", "Valor Ganho", "Valor Gasto", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
