/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalho5.view.edition;

import trabalho5.database.Event;
import trabalho5.database.Edition;
import trabalho5.view.*;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rodrigo
 */
public class SearchEdition extends javax.swing.JFrame {

    private final int type;
    
    /**
     * Creates new form SearchEdition
     * 
     * @param type
     * @param filter
     * @param value
     */
    public SearchEdition(int type, int filter, String value) {
        this.type = type;
        initComponents();
        
        // Imprime todos os eventos
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        try {
            ResultSet rs;
            // buscar por evento
            if (filter == SearchEditionByEvent.EVENT) {
                // SELECT ALL
                if (value.equals("Todos"))
                    rs = Edition.findAll(MainFrame.db);
                // SELECT BY Event
                else
                    rs = Edition.findByEvent(MainFrame.db, value);
            // buscar por local
            } else
                rs = Edition.findByLocal(MainFrame.db, value);
 
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            
            Edition ed = Edition.next(rs);
            while (ed != null) {
                // adiciona uma linha na tabela
                model.addRow(new Object[]{rs.getString("nomeEv"), ed.getNumEd(), ed.getDescricaoEd(), ed.getDataInicioEd(), 
                    ed.getDataFimEd(), ed.getLocalEd(), nf.format(ed.getTaxaEd()), nf.format(ed.getSaldoFinanceiroEd()), 
                    ed.getQtdArtigosApresentadosEd()});
                ed = Edition.next(rs);
            }
            // fecha o cursor
            MainFrame.db.close();
        } catch(SQLException e) {
            Message msg = new Message(this, true, e.getMessage());
            msg.setTitle("Erro");
            msg.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edições");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento", "Edição", "Descrição", "Data de Início", "Data de Fim", "Local", "Taxa", "Saldo", "Artigos Apresentados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(3).setMinWidth(110);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(4).setMinWidth(110);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(6).setMinWidth(70);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(7).setMinWidth(110);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(8).setMinWidth(120);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(130);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicia a tela de atualização ou remoção de evento
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (this.type != CRUDType.SEARCH) {
            // Pega a edição selecionada
            int i = this.jTable1.getSelectedRow();
            
            try {
                // pega o evento selecionado
                ResultSet rs = Event.findByName(MainFrame.db, (String) this.jTable1.getValueAt(i, 0));
                Event ev = Event.next(rs);
                int codEv = ev.getCodEv();
                // fecha o cursor
                MainFrame.db.close();
                
                String aux;
                StringBuffer tmp = new StringBuffer();
                
                aux = (String) this.jTable1.getValueAt(i, 6);
                for(int j = 0; j < aux.length(); j++) {
                    if (aux.charAt(j) >= '0' && aux.charAt(j) <= '9')
                        tmp.append(aux.charAt(j));
                    if(aux.charAt(j) == ',')
                        tmp.append(".");
                }
                double taxaEd = Double.parseDouble(tmp.toString());
                
                tmp = new StringBuffer();
                aux = (String) this.jTable1.getValueAt(i, 7);
                for(int j = 0; j < aux.length(); j++) {
                    if (aux.charAt(j) >= '0' && aux.charAt(j) <= '9')
                        tmp.append(aux.charAt(j));
                    if(aux.charAt(j) == ',')
                        tmp.append(".");
                }
                double saldoFinanceiroEd = Double.parseDouble(tmp.toString());
      
                Edition ed = new Edition(codEv, (int) this.jTable1.getValueAt(i, 1), (String) this.jTable1.getValueAt(i, 2),
                        (String) this.jTable1.getValueAt(i, 3), (String) this.jTable1.getValueAt(i, 4), 
                        (String) this.jTable1.getValueAt(i, 5), taxaEd, saldoFinanceiroEd, 
                        (int) this.jTable1.getValueAt(i, 8));
                
                // atualização da edição
                if (this.type == CRUDType.UPDATE) {
                    // inicia a interface de atualização
                    UpdateEdition updateEdition = new UpdateEdition(ed);
                    updateEdition.setVisible(true);
                    this.dispose();
                }
                // remoção da edição
                if (this.type == CRUDType.REMOVE) {
                    // inicia a interface de remoção
                    RemoveEdition removeEdition = new RemoveEdition(ed);
                    removeEdition.setVisible(true);
                    this.dispose();
                }
                
            } catch(SQLException e) {
                Message msg = new Message(this, true, e.getMessage());
                msg.setTitle("Erro");
                msg.setVisible(true);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
