/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trabalho5.view.support;
import trabalho5.database.Support;
import trabalho5.view.*;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;

import java.util.ArrayList;
import java.util.Locale;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class SearchSupport extends javax.swing.JFrame {

    private final int type;
    private final ArrayList<Support> supports;
    
    /**
     * Creates new form SearchSupport
     * 
     * @param type
     * @param name
     */
    public SearchSupport(int type, String name) {
        this.type = type;
        this.supports = new ArrayList();
        initComponents();
        
        // imprime os auxílios
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        try {
            ResultSet rs;
            // SELECT ALL
            if (name.isEmpty())
                rs = Support.findViewAll(MainFrame.db);
            // SELECT By Name
            else
                rs = Support.findViewByName(MainFrame.db, name);
            
            NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
            
            while(rs.next()) {
                // armazena os auxílios no array
                Support s = new Support(rs.getString("cnpjPat"), rs.getInt("codEvPat"), rs.getInt("numEdPat"), 
                        rs.getInt("codEvApr"), rs.getInt("numEdApr"), rs.getInt("idApr"), rs.getDouble("valorAux"), 
                        rs.getString("dataAux"), rs.getString("tipoAux"));
                this.supports.add(s);
                // adiciona uma linha na tabela
                model.addRow(new Object[] {rs.getString("nomePe"), rs.getString("razaoSocialPat"), rs.getString("nomeEv"), 
                    rs.getInt("numEdPat"), rs.getString("tipoAux"), rs.getString("dataAux"), 
                    nf.format(rs.getDouble("valorAux"))});
            }
            // fecha o cursor
            MainFrame.db.close();
            
        } catch(SQLException e) {
            Message msg = new Message(this, true, e.getMessage());
            msg.setTitle("Erro");
            msg.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auxílios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apresentador", "Patrocinador", "Evento", "Edição", "Tipo do Auxílio", "Data do Auxílio", "Valor do Auxílio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(110);
            jTable1.getColumnModel().getColumn(3).setMinWidth(40);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(4).setMinWidth(110);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(5).setMinWidth(110);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(120);
            jTable1.getColumnModel().getColumn(6).setMinWidth(110);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicia a interface de atualização ou remoção de auxílios
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (this.type != CRUDType.SEARCH) {
            // pega o auxílio selecionado
            Support s = this.supports.get(this.jTable1.getSelectedRow());
            
            // inicia a interface de atualização
            if (this.type == CRUDType.UPDATE) {
                UpdateSupport updateSupport = new UpdateSupport(s);
                updateSupport.setVisible(true);
            }
            // inicia a interface de remoção
            if (this.type == CRUDType.REMOVE) {
                RemoveSupport removeSupport = new RemoveSupport(s);
                removeSupport.setVisible(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
